name: Train a model

on:
  workflow_dispatch:
    inputs:
      model-name:
        required: true
        description: The name of the Replicate model to publish, in the format `your-replicate-username/desired-model-name`.
      prompt-identifier:
        required: true
        description: A short string like `zxz` representing your custom concept for prompts.
        default: zxz
      max-train-steps:
        required: true
        description: Number of training steps (e.g. 2000).
        type: number
        default: 2000

env:
  replicate-api-token: ${{ secrets.REPLICATE_API_TOKEN }}

jobs:
  train:
    runs-on: ubuntu-latest
    steps:

      - name: Check secrets
        if: ${{ env.replicate-api-token == '' }}
        run: |
          echo "❌ Missing REPLICATE_API_TOKEN secret!"
          exit 1
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip training data
        run: |
          zip -r data.zip data

      - name: Upload training data
        id: upload-training-data
        run: |
          echo "🔁 Получаем URL для загрузки..."
          RESPONSE=$(curl -s -X POST -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" https://dreambooth-api-experimental.replicate.com/v1/upload)
          
          echo "📦 Ответ от Replicate:"
          echo "$RESPONSE"
          
          UPLOAD_URL=$(echo "$RESPONSE" | jq -r ".upload_url")
          SERVING_URL=$(echo "$RESPONSE" | jq -r ".serving_url")

          if [ -z "$UPLOAD_URL" ] || [ -z "$SERVING_URL" ]; then
            echo "❌ Не удалось получить upload_url или serving_url. Прекращаю работу."
            exit 1
          fi

          echo "📤 Загружаем zip..."
          curl -X PUT -H "Content-Type: application/zip" --upload-file data.zip "$UPLOAD_URL"

          echo "INSTANCE_DATA_URL=$SERVING_URL" >> $GITHUB_ENV
          echo "INSTANCE_DATA_URL=$SERVING_URL" >> $GITHUB_OUTPUT

      - name: Start training
        run: |
          echo "🚀 Запускаем обучение модели..."
          curl -s -X POST \
          -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "input": {
                    "instance_prompt": "a photo of a ${{ inputs.prompt-identifier }} person",
                    "class_prompt": "a photo of a person",
                    "instance_data": "'"${{ env.INSTANCE_DATA_URL }}"'",
                    "max_train_steps": ${{ inputs.max-train-steps }}
                },
                "model": "${{ inputs.model-name }}",
                "trainer_version": "cd3f925f7ab21afaef7d45224790eedbb837eeac40d22e8fefe015489ab644aa"
              }' \
          https://dreambooth-api-experimental.replicate.com/v1/trainings

      - name: Link to model
        run: |
          echo "🚂 Модель обучается!"
          echo "Перейди на https://replicate.com/${{ inputs.model-name }} чтобы отслеживать процесс."
